apiVersion: v1
kind: ConfigMap
metadata:
  name: user-behavior-config
  namespace: user-behavior-platform
  labels:
    app.kubernetes.io/name: user-behavior-platform
    app.kubernetes.io/component: configmap
data:
  # Kafka配置
  kafka.bootstrap.servers: "kafka:9092"
  kafka.auto.create.topics.enable: "true"
  kafka.num.partitions: "3"
  
  # Redis配置
  redis.host: "redis"
  redis.port: "6379"
  
  # MySQL配置
  mysql.host: "mysql"
  mysql.port: "3306"
  mysql.database: "userdb"
  mysql.username: "user"
  
  # Eureka配置
  eureka.service.url: "http://eureka-server:8761/eureka/"
  eureka.instance.prefer.ip.address: "true"
  
  # JVM配置
  java.opts.base: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
  
  # 时区配置
  timezone: "Asia/Shanghai" 