apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  namespace: user-behavior-platform
  labels:
    app: data-collector
    app.kubernetes.io/name: data-collector
    app.kubernetes.io/component: producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: user-behavior/data-collector:1.0.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "producer"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: kafka.bootstrap.servers
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: eureka.service.url
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: eureka.instance.prefer.ip.address
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: timezone
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: java.opts.base
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: data-collector
  namespace: user-behavior-platform
  labels:
    app: data-collector
    app.kubernetes.io/name: data-collector
    app.kubernetes.io/component: producer
spec:
  selector:
    app: data-collector
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-collector-hpa
  namespace: user-behavior-platform
  labels:
    app: data-collector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-collector
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 