apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: user-behavior-platform
  labels:
    app: eureka-server
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: user-behavior/eureka-server:1.0.0
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "eureka"
        - name: SERVER_PORT
          value: "8761"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "eureka-server"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: timezone
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: user-behavior-config
              key: java.opts.base
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: user-behavior-platform
  labels:
    app: eureka-server
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
spec:
  selector:
    app: eureka-server
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP
  type: ClusterIP 