apiVersion: v1
kind: Secret
metadata:
  name: user-behavior-secrets
  namespace: user-behavior-platform
  labels:
    app.kubernetes.io/name: user-behavior-platform
    app.kubernetes.io/component: secret
type: Opaque
data:
  # MySQL密码 (base64编码)
  mysql.password: cGFzc3dvcmQ=  # password
  mysql.root.password: cm9vdHBhc3N3b3Jk  # rootpassword
  
  # Redis密码 (如果需要)
  redis.password: ""
  
  # JWT签名密钥 (如果使用)
  jwt.secret: dXNlci1iZWhhdmlvci1qd3Qtc2VjcmV0LWtleQ==  # user-behavior-jwt-secret-key 